definitions:
  dto.MemeCommon:
    properties:
      bannerUrl:
        type: string
      description:
        type: string
      logoUrl:
        type: string
      name:
        type: string
      symbol:
        type: string
    type: object
  dto.MemeDetail:
    properties:
      bannerUrl:
        type: string
      contractAddress:
        type: string
      creatorAddress:
        type: string
      decimals:
        type: integer
      description:
        type: string
      id:
        type: integer
      live:
        type: boolean
      logoUrl:
        type: string
      memeception:
        $ref: '#/definitions/dto.Memeception'
      memerc20:
        type: boolean
      name:
        type: string
      networkId:
        type: integer
      socials:
        additionalProperties:
          $ref: '#/definitions/dto.Social'
        type: object
      swapFeeBps:
        type: integer
      symbol:
        type: string
      totalSupply:
        type: string
      vestingAllocBps:
        type: integer
      website:
        type: string
    type: object
  dto.Memeception:
    properties:
      ama:
        type: boolean
      contractAddress:
        type: string
      startAt:
        type: integer
      status:
        type: integer
    type: object
  dto.MemeceptionCommon:
    properties:
      ama:
        type: boolean
      contractAddress:
        type: string
      meme:
        $ref: '#/definitions/dto.MemeCommon'
      startAt:
        type: integer
      status:
        type: integer
    type: object
  dto.MemeceptionDetailResp:
    properties:
      meme:
        $ref: '#/definitions/dto.MemeDetail'
      price:
        type: integer
    type: object
  dto.MemeceptionsResp:
    properties:
      live:
        items:
          $ref: '#/definitions/dto.MemeceptionCommon'
        type: array
      past:
        items:
          $ref: '#/definitions/dto.MemeceptionCommon'
        type: array
      upcoming:
        items:
          $ref: '#/definitions/dto.MemeceptionCommon'
        type: array
    type: object
  dto.Social:
    properties:
      displayName:
        type: string
      photoUrl:
        type: string
      provider:
        type: string
      url:
        type: string
      username:
        type: string
    type: object
  util.GeneralError:
    properties:
      code:
        description: HTTP error code, or custom error code
        type: integer
      errors:
        description: List of error send server 2 server
        items:
          type: string
        type: array
      string:
        description: Friendly error message
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This Swagger docs for membots-be.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: membots-be API
  version: "1.0"
paths:
  /api/v1/memeception:
    get:
      consumes:
      - application/json
      description: Get memeception by symbol
      parameters:
      - description: 'symbol to query, default is '
        in: query
        name: symbol
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MemeceptionDetailResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.GeneralError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/util.GeneralError'
      summary: Get memeception by symbol
      tags:
      - memeception
  /api/v1/memeceptions:
    get:
      consumes:
      - application/json
      description: Get memeceptions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MemeceptionsResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.GeneralError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/util.GeneralError'
      summary: Get memeceptions
      tags:
      - memeception
swagger: "2.0"
