definitions:
  dto.BlockchainPayload:
    properties:
      chainId:
        type: string
      creatorAddress:
        type: string
    type: object
  dto.CreateMemePayload:
    properties:
      blockchain:
        $ref: '#/definitions/dto.BlockchainPayload'
      memeInfo:
        $ref: '#/definitions/dto.MemeInfoPayload'
      memeception:
        $ref: '#/definitions/dto.MemeceptionPayload'
      socials:
        additionalProperties:
          $ref: '#/definitions/dto.Social'
        type: object
    type: object
  dto.LaunchpadInfo:
    properties:
      collectedETH:
        type: string
      status:
        type: string
      targetETH:
        type: string
      transactions:
        items:
          $ref: '#/definitions/dto.Transaction'
        type: array
    type: object
  dto.LaunchpadInfoResp:
    properties:
      launchpadInfo:
        $ref: '#/definitions/dto.LaunchpadInfo'
    type: object
  dto.LaunchpadTx:
    properties:
      amountUSD:
        type: string
      logoUrl:
        type: string
      memeContractAddress:
        type: string
      symbol:
        type: string
      txHash:
        type: string
      txType:
        type: string
      walletAddress:
        type: string
    type: object
  dto.MemeCommon:
    properties:
      bannerUrl:
        type: string
      contract_address:
        type: string
      description:
        type: string
      logoUrl:
        type: string
      meta:
        type: string
      name:
        type: string
      symbol:
        type: string
    type: object
  dto.MemeDetail:
    properties:
      bannerUrl:
        type: string
      contractAddress:
        type: string
      creatorAddress:
        type: string
      decimals:
        type: integer
      description:
        type: string
      id:
        type: integer
      live:
        type: boolean
      logoUrl:
        type: string
      memeception:
        $ref: '#/definitions/dto.Memeception'
      meta:
        type: string
      name:
        type: string
      networkId:
        type: integer
      socials:
        additionalProperties:
          $ref: '#/definitions/dto.Social'
        type: object
      swapFeeBps:
        type: integer
      symbol:
        type: string
      totalSupply:
        type: string
      vestingAllocBps:
        type: integer
      website:
        type: string
    type: object
  dto.MemeInfoPayload:
    properties:
      ama:
        type: boolean
      bannerUrl:
        type: string
      description:
        type: string
      logoUrl:
        type: string
      meta:
        type: string
      name:
        type: string
      salt:
        type: string
      swapFeeBps:
        type: string
      swapFeePct:
        type: number
      symbol:
        type: string
      targetETH:
        type: number
      telegram:
        type: string
      vestingAllocBps:
        type: string
      website:
        type: string
    type: object
  dto.Memeception:
    properties:
      ama:
        type: boolean
      collectedETH:
        type: string
      contractAddress:
        type: string
      enabled:
        type: boolean
      meme:
        $ref: '#/definitions/dto.MemeCommon'
      memeID:
        type: integer
      startAt:
        type: integer
      status:
        type: integer
      targetETH:
        type: string
      updatedAtEpoch:
        type: integer
    type: object
  dto.MemeceptionByStatus:
    properties:
      live:
        items:
          $ref: '#/definitions/dto.Memeception'
        type: array
      past:
        items:
          $ref: '#/definitions/dto.Memeception'
        type: array
    type: object
  dto.MemeceptionDetailResp:
    properties:
      meme:
        $ref: '#/definitions/dto.MemeDetail'
      price:
        type: integer
    type: object
  dto.MemeceptionPayload:
    properties:
      ema:
        type: boolean
      startAt:
        type: string
      targetETH:
        type: string
    type: object
  dto.MemeceptionsResp:
    properties:
      latestCoins:
        items:
          $ref: '#/definitions/dto.Memeception'
        type: array
      latestLaunchpadTx:
        items:
          $ref: '#/definitions/dto.LaunchpadTx'
        type: array
      memeceptionsByStatus:
        $ref: '#/definitions/dto.MemeceptionByStatus'
      price:
        type: integer
    type: object
  dto.Social:
    properties:
      displayName:
        type: string
      photoUrl:
        type: string
      provider:
        type: string
      url:
        type: string
      username:
        type: string
    type: object
  dto.Swap:
    properties:
      amount0:
        type: string
      amount1:
        type: string
      amountUSD:
        type: string
      buy:
        type: boolean
      priceETH:
        type: string
      priceUSD:
        type: string
      swapAt:
        type: integer
      token1IsMeme:
        type: boolean
      txHash:
        type: string
      walletAddress:
        type: string
    type: object
  dto.SwapHistoryByAddressResp:
    properties:
      swaps:
        items:
          $ref: '#/definitions/dto.Swap'
        type: array
    type: object
  dto.Transaction:
    properties:
      amountETH:
        type: string
      amountMeme:
        type: string
      epoch:
        type: integer
      memeId:
        type: string
      txHash:
        type: string
      txType:
        type: string
      walletAddress:
        type: string
    type: object
  util.GeneralError:
    properties:
      code:
        description: HTTP error code, or custom error code
        type: integer
      errors:
        description: List of error send server 2 server
        items:
          type: string
        type: array
      string:
        description: Friendly error message
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/launchpad:
    get:
      consumes:
      - application/json
      description: Get launchpad history by address
      parameters:
      - description: 'memeAddress to query, default is '
        in: query
        name: memeAddress
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LaunchpadInfoResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.GeneralError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/util.GeneralError'
      summary: Get launchpad history by address
      tags:
      - launchpad
  /api/v1/meme:
    get:
      consumes:
      - application/json
      description: Get memeception by meme address
      parameters:
      - description: 'memeAddress to query, default is '
        in: query
        name: memeAddress
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MemeceptionDetailResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.GeneralError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/util.GeneralError'
      summary: Get memeception by meme address
      tags:
      - memeception
  /api/v1/memeceptions:
    get:
      consumes:
      - application/json
      description: Get memeceptions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MemeceptionsResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.GeneralError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/util.GeneralError'
      summary: Get memeceptions
      tags:
      - memeception
  /api/v1/memes:
    post:
      consumes:
      - application/json
      description: Create meme
      parameters:
      - description: Request create meme, required
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.CreateMemePayload'
      produces:
      - application/json
      responses:
        "200":
          description: 'When success, return {"success": true}'
          schema:
            $ref: '#/definitions/dto.CreateMemePayload'
        "417":
          description: Expectation Failed
          schema:
            $ref: '#/definitions/util.GeneralError'
        "424":
          description: Failed Dependency
          schema:
            $ref: '#/definitions/util.GeneralError'
      summary: Create meme
      tags:
      - memeception
  /api/v1/quote:
    get:
      consumes:
      - application/json
      description: Swap router
      parameters:
      - description: protocols to query, default is v3
        in: query
        name: protocols
        type: string
      - description: tokenInAddress to query
        in: query
        name: tokenInAddress
        type: string
      - description: tokenInChainId to query
        in: query
        name: tokenInChainId
        type: string
      - description: tokenOutAddress to query
        in: query
        name: tokenOutAddress
        type: string
      - description: tokenOutChainId to query
        in: query
        name: tokenOutChainId
        type: string
      - description: amount to query
        in: query
        name: amount
        type: string
      - description: type to query
        in: query
        name: type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.GeneralError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/util.GeneralError'
      summary: Swap router
      tags:
      - swap
  /api/v1/swaps:
    get:
      consumes:
      - application/json
      description: Get swaps history by memeId
      parameters:
      - description: 'memeId to query, default is '
        in: query
        name: memeId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SwapHistoryByAddressResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.GeneralError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/util.GeneralError'
      summary: Get swaps history by memeId
      tags:
      - swap
swagger: "2.0"
