definitions:
  dto.Meme20MetaDto:
    properties:
      created_at:
        type: string
      creator_allocation_vestedy:
        type: string
      creator_swap_fee:
        type: string
      description:
        type: string
      fair_lauch_type:
        type: string
      id:
        type: integer
      meme_type:
        type: string
      telegram_url:
        type: string
      ticker:
        type: string
      twitter_url:
        type: string
      updated_at:
        type: string
    type: object
  util.GeneralError:
    properties:
      code:
        description: HTTP error code, or custom error code
        type: integer
      errors:
        description: List of error send server 2 server
        items:
          type: string
        type: array
      string:
        description: Friendly error message
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This Swagger docs for membots-be.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: membots-be API
  version: "1.0"
paths:
  /api/v1/module/fair_lauch/meme/{ticker}:
    get:
      consumes:
      - application/json
      description: Get Meme20 metadata by ticker
      parameters:
      - description: ticker to query
        in: query
        name: ticker
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Meme20MetaDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.GeneralError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/util.GeneralError'
      summary: Get Meme20 metadata by ticker
      tags:
      - category
swagger: "2.0"
