name: Production deployment
on:
  push:
    branches: ['main']

jobs:
  build-image:
    uses: AstraProtocol/github-actions-workflows/.github/workflows/stella-deployment.yml@main
    with:
      ingressEnabled: "yes"
      ingressHost: "affiliate-system.prod.astranet.services"
      replicas: "1"
      servicePort: "8080"
    secrets: inherit
